[tool.poetry]
name = "trello-python-cfd"
version = "0.1.0"
description = ""
authors = ["John Stephenson <johnnyfleet@gmail.com>"]
readme = "README.md"
packages = [{include = "trello_python_cfd"}]

[tool.poetry.dependencies]
python = "^3.11"
jq = "^1.4.1"
gql = "^3.4.1"
ipykernel = "^6.24.0"
aiohttp = "^3.8.4"
glom = "^23.3.0"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
