[tool.poetry]
name = "trello-python-cfd"
version = "0.1.0"
description = ""
authors = ["John Stephenson <johnnyfleet@gmail.com>"]
readme = "README.md"
packages = [{include = "trello_python_cfd"}]

[tool.poetry.dependencies]
python = "^3.11"
ipykernel = "^6.25.1"
requests = "^2.31.0"
pandas = "^2.0.3"
nbconvert = "^7.7.3"
requests-oauthlib = "^1.3.1"
plotly = "^5.16.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
